### ISSUE TITLE
Zarf connect does not work for named ports

### ISSUE THREAD

**Issue by robmcelvenny** [defenseunicorns/zarf#1693]
### Environment
Device and OS: macOS m2
App version: zarf 0.26.1
Kubernetes distro being used: v1.26.4+k3s1

When zarf connect references a service that is using a named port the port is parsed to ZERO rather than the value that is defined in the underlying pods.

### Steps to reproduce
1. Deploy podinfo as a zarf package
2. Add zarf connect label(s) to podinfo service
3. Attempt to zarf connect podinfo 

### Expected result
```
❯ zarf connect podinfo -l trace
DEBUG   2023-05-10T16:53:20-04:00  -  tunnel.Connect(podinfo, true)
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:112)
  DEBUG   2023-05-10T16:53:20-04:00  -  tunnel.checkForZarfConnectLabel(podinfo)
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:112)
  DEBUG   2023-05-10T16:53:20-04:00  -  tunnel connection match: podinfo/podinfo on port 9898
  ```

### Actual Result
```
❯ zarf connect podinfo -l trace
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:112)
  DEBUG   2023-05-10T16:55:08-04:00  -  tunnel.Connect(podinfo, true)
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:112)
  DEBUG   2023-05-10T16:55:08-04:00  -  tunnel.checkForZarfConnectLabel(podinfo)
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:112)
  DEBUG   2023-05-10T16:55:08-04:00  -  tunnel connection match: podinfo/podinfo on port 0
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:112)
```

### Severity/Priority
low

### Additional Context
Pod spec
```
      name: podinfo
      ports:
      - containerPort: 9898
        name: http
        protocol: TCP
      - containerPort: 9797
        name: http-metrics
        protocol: TCP
      - containerPort: 9999
        name: grpc
        protocol: TCP
```

Service
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    zarf.dev/connect-description: podinfo!!!
    zarf.dev/connect-url: ?podinfo
  labels:
    zarf.dev/connect-name: podinfo
spec:
  ...
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http
```

### Suggested resolution
https://github.com/defenseunicorns/zarf/blob/c9cdce4e9439ef8c625c65b99376b64df108cca5/src/internal/cluster/tunnel.go#LL363C1-L363C1

The line that parses the port values does not understand the differences between string / port so if there is a named port it will fail to parse properly and result in a nil value.

**Comment by cmwylie19** [comment]
Adding a little context here

```bash
└─[1] <git:(1849 9b75e7a0✱✈) > zarf connect prometheus-operated-agent -l trace
  DEBUG   2023-07-05T11:46:17-04:00  -  Log level set to trace
└ (/home/runner/work/zarf/zarf/src/cmd/root.go:113)

Saving log file to
/var/folders/v0/slmrzc4s6kx4n7jb77ch9fc80000gn/T/zarf-2023-07-05-11-46-17-330021674.log
  DEBUG   2023-07-05T11:46:17-04:00  -  tunnel.NewTunnel(zarf, svc, , 0, 0)                                                                                                                                                                          
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:118)
  DEBUG   2023-07-05T11:46:17-04:00  -  k8s.NewK8sClient()                                                                                                                                                                                           
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:118)
  DEBUG   2023-07-05T11:46:18-04:00  -  tunnel.Connect(prometheus-operated-agent, true)                                                                                                                                                              
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:118)
  DEBUG   2023-07-05T11:46:18-04:00  -  tunnel.checkForZarfConnectLabel(prometheus-operated-agent)                                                                                                                                                   
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:118)
  DEBUG   2023-07-05T11:46:18-04:00  -  tunnel connection match: monitoring/prometheus-operated-agent on port 0                                                                                                                                      
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:118)
  DEBUG   2023-07-05T11:46:18-04:00  -  missing remote port                                                                                                                                                                                          
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:154)
     ERROR:  Unable to connect to the service: missing remote port
└ (/home/runner/work/zarf/zarf/src/pkg/message/spinner.go:157)
  DEBUG   2023-07-05T11:46:18-04:00  -  goroutine 1 [running]:
          runtime/debug.Stack()
                /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/debug/stack.go:24 +0x64
          github.com/defenseunicorns/zarf/src/pkg/message.Fatal({0x108b046e0?, 0x1400039eb90?}, {0x14000553440, 0x35})
                /home/runner/work/zarf/zarf/src/pkg/message/message.go:156 +0x14c
          github.com/defenseunicorns/zarf/src/pkg/message.Fatalf({0x108b046e0, 0x1400039eb90}, {0x106f9a9bd?, 0x106efba30?}, {0x1400189fd28?, 0x1089e7260?, 0x10aeb5c01?})
                /home/runner/work/zarf/zarf/src/pkg/message/message.go:163 +0x54
          github.com/defenseunicorns/zarf/src/pkg/message.(*Spinner).Fatalf(0x14000b032d8?, {0x10911a680?, 0x1400039eb90?}, {0x106f9a9bd?, 0x24?}, {0x1400189fd28?, 0x1?, 0x1?})
                /home/runner/work/zarf/zarf/src/pkg/message/spinner.go:157 +0xd0
          github.com/defenseunicorns/zarf/src/cmd.glob..func1(0x10b0f4bc0?, {0x14001718450?, 0x3?, 0x3?})
                /home/runner/work/zarf/zarf/src/cmd/connect.go:46 +0x1c8
          github.com/spf13/cobra.(*Command).execute(0x10b0f4bc0, {0x140017183f0, 0x3, 0x3})
                /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
          github.com/spf13/cobra.(*Command).ExecuteC(0x10b0f8de0)
                /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
          github.com/spf13/cobra.(*Command).Execute(...)
                /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
          github.com/defenseunicorns/zarf/src/cmd.Execute()
                /home/runner/work/zarf/zarf/src/cmd/root.go:68 +0x28
          main.main()
                /home/runner/work/zarf/zarf/main.go:23 +0x9c
└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:156)
```
